# Generated by Django 5.1.2 on 2024-11-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='form',
            name='text_color',
        ),
    ]
