# Generated by Django 5.1.3 on 2024-11-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_form', '0003_remove_form_allow_view_score_remove_form_is_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_republish',
            field=models.BooleanField(default=False),
        ),
    ]
